---
- name: Install automysqlbackup
  apt: name={{item}} state=present
  with_items:
  - automysqlbackup
  when: ansible_distribution == "Ubuntu"  

- name: Configure automysqlbackup
  template: src=automysqlbackup.j2 dest=/etc/default/automysqlbackup
  when: ansible_distribution == "Ubuntu"
