---
- name: Remove existing java from ubuntu
  apt: name={{item}} state=absent
  with_items:
  - oracle-java8-installer
  - openjdk-8-jdk
  when: ansible_distribution == "Ubuntu"

- name: Remove existing java from centos
  yum: name={{item}} state=removed
  with_items:
  - java-1.8.0-openjdk-devel
  when: ansible_distribution == "CentOS"

- name: Download jdk archive
  get_url: url='{{jdk_download_url}}{{jdk_version}}.tar' dest='{{jdk_directory}}/{{jdk_version}}.tar'

- name: Extract jdk archive
  unarchive: src="{{jdk_directory}}/{{jdk_version}}.tar" dest="{{jdk_directory}}" remote_src=yes

- name: Create java symlinks
  file: src="{{item.src}}" dest="{{item.dest}}" state=link
  with_items:
  - {src: "{{jdk_directory}}/{{jdk_version}}", dest: "{{jdk_directory}}/java_home"}
  - {src: "{{jdk_directory}}/java_home/bin/java", dest: "/usr/bin/java"}
  - {src: "{{jdk_directory}}/java_home/bin/javac", dest: "/usr/bin/javac"}
  - {src: "{{jdk_directory}}/java_home/bin/jar", dest: "/usr/bin/jar"}

- name: Set environment variables
  template: src=java_home.sh.j2 dest=/etc/profile.d/java_home.sh

- name: Clean up
  file: path="{{jdk_directory}}/{{jdk_version}}.tar" state=absent
