---
#初始化,关闭防火墙和SELINUX
- hosts: CentOS6
  tasks:
#    - name: off selinux
#      shell: setenforce 0
    - name: selinux modify enforcing
      lineinfile:
        dest: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
    - name:  add iptables
      shell: iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 10050 -j ACCEPT
#安装zabbix_client
- hosts: CentOS6
  vars:
    zabbix_proxy_ip: 10.11.10.168
    zabbix_agent_ip: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
  tasks:
    - name: install zabbix_client
      shell: rpm -ivh http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-release-3.0-1.el6.noarch.rpm
    - name: Install zabbix agent
      shell: yum -y install zabbix-agent
    - name: modify zabbix server ip address
      shell: sed -i 's#Server=127.0.0.1#Server='{{zabbix_proxy_ip}}'#g' /etc/zabbix/zabbix_agentd.conf
    - name: modify zabbix server active ip addr
      shell: sed -i 's/ServerActive=127.0.0.1/ServerActive='{{zabbix_proxy_ip}}'/g' /etc/zabbix/zabbix_agentd.conf
    - name: Enable remote command execution
      shell: sed -i 's/# EnableRemoteCommands=0/EnableRemoteCommands=1'/g /etc/zabbix/zabbix_agentd.conf
    - name: Enable remote command logs
      shell: sed -i 's/# LogRemoteCommands=0/LogRemoteCommands=1'/g /etc/zabbix/zabbix_agentd.conf
    - name: modify zabbix agent hostname
      shell: sed -i 's/Hostname=Zabbix server/Hostname='{{zabbix_agent_ip}}'/g' /etc/zabbix/zabbix_agentd.conf
    - name: enable zabbix-agent
      shell: /etc/init.d/zabbix-agent start;chkconfig zabbix-agent on
