---
#初始化,关闭防火墙和SELINUX
- hosts: CentOS7
  tasks:
    - name: off selinux
      shell: setenforce 0
    - name: selinux modify enforcing
      lineinfile:
        dest: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
    - name: stop firewalld
      shell: systemctl stop firewalld && systemctl disable firewalld
#安装zabbix_client
- hosts: CentOS7
  vars:
    zabbix_proxy_ip: 10.11.10.168
    zabbix_agent_ip: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
  tasks:
    - name: install zabbix_client
      shell: rpm -ivh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    - name: Install zabbix agent
      shell: yum -y install zabbix-agent
    - name: modify zabbix server ip address
      shell: sed -i 's#Server=127.0.0.1#Server='{{zabbix_proxy_ip}}'#g' /etc/zabbix/zabbix_agentd.conf
    - name: modify zabbix server active ip addr
      shell: sed -i 's/ServerActive=127.0.0.1/ServerActive='{{zabbix_proxy_ip}}'/g' /etc/zabbix/zabbix_agentd.conf
    - name: Enable remote command execution
      shell: sed -i 's/# EnableRemoteCommands=0/EnableRemoteCommands=1'/g /etc/zabbix/zabbix_agentd.conf
    - name: Enable remote command logs
      shell: sed -i 's/# LogRemoteCommands=0/LogRemoteCommands=1'/g /etc/zabbix/zabbix_agentd.conf
    - name: modify zabbix agent hostname
      shell: sed -i 's/Hostname=Zabbix server/Hostname='{{zabbix_agent_ip}}'/g' /etc/zabbix/zabbix_agentd.conf
    - name: enable zabbix-agent
      shell: systemctl start zabbix-agent ;systemctl enable zabbix-agent
